<a href="https://colab.research.google.com/github/amrit2711tech/Assignment/blob/main/Amritpreet_kaur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


#Assignment No. 1

In [ ]:
#Create variables to store your name (string), age (integer), and course (string). Print all of them
#using a single print() statement.
Name, Age, Course="amrit",20,"Btech"

print(Name,Age,Course)

amrit 20 Btech


In [ ]:
#Write a program to swap two numbers without using a third variable. Example: a = 4, b = 9.
x=4
y=9
x,y=y,x
print(x)

9


In [ ]:
#Arithmetic operations
x=20
y=15

print(x+y) #sum
print(x-y )#difference
print(x/y) #divide
print(x%y) #remainder
print(x*y) #product

35
5
1.3333333333333333
5
300


In [ ]:
#Take marks of 5 subjects and calculate the total and percentage
a=80 #subject1
b=97 #subject2
c=78 #subject3
d=89 #subject4
e=85 #subject5

total= a+b+c+d+e
print (total)
percentage= total/500*100
print(percentage)


429
85.8


In [ ]:
#Use compound assignment operators
x = 10
print(x)

x += 5
print(x)

x *= 2
print(x)

x -= 4
print(x)

x /= 2
print(x)


10
15
30
26
13.0


In [ ]:
#Relational operator check
a = 10 # first number
b = 7 #second number

if a == b:
    print("Both are equal")
elif a > b:
    print("First is greater")
else:
    print("Second is greater")


First is greater


In [ ]:
# Logical operator challenge
is_raining = True
have_umbrella = False

print(is_raining & have_umbrella)

print(is_raining | have_umbrella)

if not is_raining or (is_raining and have_umbrella): #not is_raining= false
    print("You can go outside.")                     # is_raining and have_umbrella= false then it gives output false
else:                                                #false or false gives false
    print("You cannot go outside.")

False
True
You cannot go outside.


In [ ]:
#Identity operator
list1 = [1, 2, 3]
list2 = [3, 2, 1]

print(list1 == list2)
print(list1 is list2)

False
False


In [ ]:
#Bitwise operation
a=17
b=23

print(a & b) #AND
print(a|b)  #OR
print(a^b)   #XOR

17
23
6


In [ ]:
# Variable types and typecasting
a = 5
b =4.5

print("Type of int_num:", type(a))
print("Type of float_num:", type(b))

sum  = a+b
print("Sum as integer:",(sum))


Type of int_num: <class 'int'>
Type of float_num: <class 'float'>
Sum as integer: 9.5


#Assignment No. 2

In [ ]:
#to print number 1 to 10 but stop the loop when number reaches 9
for i in range(1,14):
    if i==9:
        break
    print(i)

1
2
3
4
5
6
7
8


In [ ]:
#enter the number
num=int(input("enter the number"))
if num>=0:
    print("enter the number:",num)
else:
    print("stop,you enter the negative number",num)

enter the number5
enter the number: 5


In [ ]:
#find first even number in a list
list=[1,2,5,8,11,14]
for num in list:
    if num%2==0:
        print("first even number is:",num)
        break

first even number is: 2


In [ ]:
#sum exceeds 25
A=[5,10,5,7,9,11,15]
total=0
for a in A:
    total+=a
    if total>=25:
        print("total sum:",total)
        print("last number added:",a)

total sum: 27
last number added: 7
total sum: 36
last number added: 9
total sum: 47
last number added: 11
total sum: 62
last number added: 15


In [ ]:
#guess da password
while True:
    password=input("enter the password")
    if password=="admin123":
        print("access granted")
        break
    else:
        print("guess the password")

enter the passwordadmin123
access granted


In [ ]:
#print multiplies of 7 stop the value is greater than 100
i=1
while True:
    result=7*i
    if result>100:
        break
    print(f"7*{i}={result}")
    i+=1

7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70
7*11=77
7*12=84
7*13=91
7*14=98


In [ ]:
#print multiplies of 7 stop the value is greater than 100
i=1
while True:
    result=7*i
    if result>100:
        break
    print(f"7*{i}={result}")
    i+=1

7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70
7*11=77
7*12=84
7*13=91
7*14=98


#Assignment 3

In [ ]:
#REVERSE WORDS IN SENTENCE
sentence="i love python"
words=sentence.split()
words.reverse()
reversed_sentence=' '.join(words)
print(reversed_sentence)

python love i


In [ ]:
#COUNT CONSONANTS:
string="hello world"
vowels='aeiouAEIOU'
count=0
for ch in string:
    if ch.isalpha() and ch not in vowels:
        count+=1
print(count)

7


In [ ]:
#CHECK IF TWO STRINGS ARE ANAGRAMS
s1="Listen"
s2="Silent"
s1_sorted=sorted(s1.lower())
s2_sorted=sorted(s2.lower())
if s1_sorted==s2_sorted:
    print("Anagram")
else:
    print("Not Anagram")

Anagram


In [ ]:
#FIRST UNIQUE CHARACTER
string="swiss"
for ch in string:
    if string.count(ch)==1:
        print(ch)
        break


w


In [ ]:
#COMPRESS STRING
s="aaabbc"
compressed=""
i=0
while i<len(s):
    count=1
    while i+1<len(s) and s[i]==s[i+1]:
        count+=1
        i+=1
    compressed+=s[i]+str(count)
    i+=1
if len(compressed)<len(s):
    print(compressed)
else:
    print(s)


aaabbc


In [ ]:
#LONGEST PALINDROMIC SUBSTRING:
s="babad"
max_len=0
result=""
for i in range(len(s)):
    for j in range(i+1,len(s)+1):
        substr=s[i:j]
        if substr==substr[::-1] and len(substr)>max_len:
            result=substr
            max_len=len(substr)
print(result)


In [ ]:
#VALID PARENTHESES
s="({[]})"
stack=[]
mapping={')':'(','}':'{',']':'['}
valid=True
for ch in s:
    if ch in mapping.values():
        stack.append(ch)
    elif ch in mapping:
        if not stack or stack.pop()!=mapping[ch]:
            valid=False
            break
if stack:
    valid=False
print("valid"if valid else"invalid")


valid


In [ ]:
#word ladder transformation steps
from collections import deque
start="hit"
end="cog"
wordlist=["hot","dot","dog","lot","log","cog"]
wordSet=set(wordlist)
queue=deque([(start,1)])
while queue:
    word,steps=queue.popleft()
    if word==end:
        print(steps)
        break
    for i in range(len(word)):
        for c in'abcdefghijklmnopqrstuvwxyz':
           next_word=word[:i]+c+word[i+1:]
           if next_word in wordSet:
             wordSet.remove(next_word)
             queue.append((next_word,steps+1))
else:
    print(0)


5


#Assignment 4

In [ ]:
Class= {"student1":55,
       "student2":69,
       "student3":77,
       "student4":89,
       "student5":45}
print(Class)


{'student1': 55, 'student2': 69, 'student3': 77, 'student4': 89, 'student5': 45}


In [ ]:
#COUNT THE FREQUENCY OF EACH CHARACTER IN A GIVEN STRING
string="hello amrit"
freq={}

for char in string:
    if char!=" ":
        freq[char]=freq.get(char,0)+1
print(freq)


{'h': 1, 'e': 1, 'l': 2, 'o': 1, 'a': 1, 'm': 1, 'r': 1, 'i': 1, 't': 1}


In [ ]:
#PRINT THE NAME OF THE OLDEST PERSON
Person={"person1":56,"person2":33,"person3":18,"person4":65,"person5":40}
oldest_person=max(Person,key=Person.get)
print("the oldest person is:",oldest_person)


the oldest person is: person4


In [ ]:
#MERGE TWO DICTIONARIES
dict1={"aman":1,"anmol":2,"arsh":3}
dict2={"diljeet":4,"dilpreet":5}
dict3=dict1|dict2
print(dict3)


{'aman': 1, 'anmol': 2, 'arsh': 3, 'diljeet': 4, 'dilpreet': 5}


In [ ]:
#KEYS ARE NUMBER BETWEEN 1 TO 10 AND VALUES ARE THEIR SQUARE
dict={x:x**2 for x in range(1,11)}
print(dict)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
#INVERTS A DICTIONARY
dict={'a':1,'b':2,'c':3,'d':4}
inverted_dict={value:key for key,value in dict.items()}
print("inverted dictionary is:",inverted_dict)


inverted dictionary is: {1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [ ]:
#NESTED DICTIONARY OF STUDENTS AND THEIR SUBJECT WISE MARKS.CALCULATE AND PRINT AVERAGE MARKS FOR STUDENT
students={"student1":{'eng':55,'pbi':44,'math':60,'sci':33,'sst':44},
          "student2":{'eng':45,'pbi':74,'math':60,'sci':83,'sst':94},
          "student3":{'eng':57,'pbi':94,'math':40,'sci':53,'sst':34},
          "student4":{'eng':45,'pbi':54,'math':50,'sci':43,'sst':54},
          }
for name,subjects in students.items():
    avg=sum(subjects.values())/len(subjects)
    print(name,"average is",avg)


student1 average is 47.2
student2 average is 71.2
student3 average is 55.6
student4 average is 49.2


In [ ]:
#GROUP WORDS BY THEIR LENGTH FROM A LIST USING DICTIONARY
list=['apple','banana','orange','guava','papaya','kiwi','chiku']
group={}
for word in list:
    l=len(word)
    group.setdefault(l,[]).append(word)
print(group)


{5: ['apple', 'guava', 'chiku'], 6: ['banana', 'orange', 'papaya'], 4: ['kiwi']}


In [ ]:
#Create a program that takes a list of tuples (name, score) and builds a dictionary
#where each name is a key, and the value is a list of all their scores. Then calculate and print
#each person's average score.
list=[('aman',78),('avrit',44),('komal',55),('dilpreet',66),
      ('aman',78),('avrit',44),('komal',55),('dilpreet',66)]
score_dict={}
for name,score in list:
    if name in score_dict:
        score_dict[name].append(score)
    else:
        score_dict[name]=[score]
print(score_dict)
for name,score in score_dict.items():
    avg=sum(score)/len(score)
    print(name,"average is",avg)


{'aman': [78, 78], 'avrit': [44, 44], 'komal': [55, 55], 'dilpreet': [66, 66]}
aman average is 78.0
avrit average is 44.0
komal average is 55.0
dilpreet average is 66.0


#Assignment 5

In [ ]:
#wap to make a pyramid
rows=int(input("enter the number of rows:"))
for i in range(1,rows+1):
    print(" "*(rows-i),end="")
    print("*"*(2*i-1))


enter the number of rows:5
    *
   ***
  *****
 *******
*********


In [ ]:
#create a pattern
rows=int(input("enter the number of rows:"))
for i in range(1,rows+1):
    print("*"*i)


enter the number of rows:4
*
**
***
****


In [ ]:
#create a square pattern
size=int(input("enter the size of square:"))
for i in range(size):
    print("*"*size)


enter the size of square:4
****
****
****
****


In [ ]:
#create a circular pattern
import math
radius=int(input("enter radius of the circle:"))
for y in range(-radius,radius+1):
    for x in range(-radius,radius+1):
        if abs(x**2+y**2-radius**2)<radius:
            print("*",end="")
        else:
            print(" ",end="")
    print()


enter radius of the circle:4
   ***   
 **   ** 
 *     * 
*       *
*       *
*       *
 *     * 
 **   ** 
   ***   


In [ ]:
#create a rectangular pattern
rows=int(input("enter the number of rows:"))
columns=int(input("enter the number of columns:"))
for i in range(rows):
    print("*"*columns)


enter the number of rows:4
enter the number of columns:5
*****
*****
*****
*****


#Assignment 6

In [ ]:
#TO CREATE A TULE WITH DIFFERENT DATA TYPES AND PRINT ITS TYPE
tuple=("hello",2,3.14,True)
print(tuple)
print("type:",type(tuple))


('hello', 2, 3.14, True)
type: <class 'tuple'>


In [ ]:
#GIVEN A TUPLE t=(10,20,30,40,50),write a program to access the second last element
t=(10,20,30,40,50)
second_last_element=t[-2]
print("second last element is:",second_last_element)


second last element is: 40


In [ ]:
#to count number of times a given element appears in a tuple
tuple=(2,5,6,4,8,10,4,6,6,9,10)
t=tuple.count(6)
print(t)


3


In [ ]:
#to convert a tuple of strings into a single string.example:('python','is','fun')
tuple=('python','is','fun')
single_string=' '.join(tuple)
print(single_string)


python is fun


In [ ]:
#to find the index of an element in a tuple
tuple=(2,5,6,8,9,10)
t=tuple.index(9)
print(t)


4


In [ ]:
#create two sets and perform union,intersection,and difference operations
set1={'apple','mango','banana','orange','chiku'}
set2={'muskmelon','strawberry','kiwi','melon'}
union=set1.union(set2)
print("union:",union)
intersection=set1.intersection(set2)
print("intersection:",intersection)
difference=set1.difference(set2)
print("difference:",difference)


union: {'orange', 'banana', 'apple', 'mango', 'melon', 'chiku', 'strawberry', 'muskmelon', 'kiwi'}
intersection: set()
difference: {'orange', 'banana', 'apple', 'mango', 'chiku'}


In [ ]:
#check if a given element is present in a set or not
set1={'apple','banana','mango','watermelon','papaya'}
element=input("enter an element to check:")
if element in set1:
    print(f"{element} is present in the set")
else:
    print(f"{element} is not present in the set")


enter an element to check:kiwi
kiwi is not present in the set


In [ ]:
#to remove duplicate elements from a list using a set
my_list=[10,20,30,40,50,10,20,20,90]
unique_list= list(set(my_list))
print("original list:",my_list)
print("list after removing duplicates:",unique_list)


original list: [10, 20, 30, 40, 50, 10, 20, 20, 90]
list after removing duplicates: [40, 10, 50, 20, 90, 30]


In [ ]:
#find symmetric difference between two sets
set1={'apple','mango','orange','kiwi','melon'}
set2={'strawberry','kiwi','watermelon'}
symmetric_diff=set1.symmetric_difference(set2)
print(symmetric_diff)


{'orange', 'apple', 'mango', 'strawberry', 'watermelon', 'melon'}


In [ ]:
#given a list of numbers,write a python program to find all unique elements using sets
#python now thinks set is a dictionary,not the actual built.in set() function.
list=[2,1,3,5,6,2,4,8,9,10,5,6,7]
unique_elements=set(list)
print("unique elements are:",unique_elements)


unique elements are: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


#Assignment 7

In [ ]:
#Write a function to find the factorial of a number using recursion
def fact(n):
    if n<0:
        return "factorial is not defined for negative numbers"
    elif n==0 or n==1:
        return 1
    else:
        result=1
        for i in range(2,n+1):
            result*=i
        return result
print(fact(8))


40320


In [ ]:
#Write a function that checks whether a number is prime or not
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True
print(is_prime(7))


True


In [ ]:
#Create a function that takes a string as input and returns the
# number of vowels in it.
def count_vowels(s):
    vowels='aeiouAEIOU'
    count=0
    for char in s:
        if char in vowels:
            count+=1
    return count
text=input("enter the string:")
print("Number of vowels:",count_vowels(text))


enter the string:amritpreet kaur
Number of vowels: 6


In [ ]:
#Write a function that accepts a list of numbers and
# returns the maximum and minimum values.
def max_min(number):
    maxi=max(number)
    mini=min(number)
    return maxi,mini
x=list(map(int,input("enter a list of numbers separated by comma(,):").split(",")))
maxi,mini=max_min(x)
print(f"maximum value:{maxi}")
print(f"minimum value:{mini}")


enter a list of numbers separated by comma(,):1,2,44,555
maximum value:555
minimum value:1


In [ ]:
#Write a Python function to calculate the nth Fibonacci number using recursion
def fibonacci(n):
    if n<=0:
        return 0
    elif n==1:
        return 1
    else:
        return fibonacci(n-1)+fibonacci(n-2)
n=int(input("enter any number:"))
print(f"the{n}th fibonacci number is:",fibonacci(n))


enter any number:33
the33th fibonacci number is: 3524578


In [ ]:
# Create a function that accepts two numbers and returns
#  their greatest common divisor (GCD).
import math
def gcd(a,b):
    return math.gcd(a,b)
num1=int(input("enter the num1:"))
num2=int(input("enter the num2:"))
print("GCD IS:",gcd(num1,num2))


enter the num1:36
enter the num2:64
GCD IS: 4


In [ ]:
# Write a function that takes a list and returns a new list
# with only unique elements
def unique_elements(list1):
    return list(set(list1))
my_list=list(input("enter a list separated by a comma(,):").split(','))
print(f"unique elements is:{unique_elements(my_list)}")


enter a list separated by a comma(,):2,44,44,55,79,79,90
unique elements is:['55', '44', '79', '2', '90']


In [ ]:
# Write a function to count the frequency of each word in a given string
def word_frequency(s):
    words=s.split()
    freq={}
    for word in words:
        word=word.lower()
        freq[word]=freq.get(word,0)+1
    return freq
text=input("enter a string separated by a space:")
print(word_frequency(text))


enter a string separated by a space:THE cat this is the cat
{'the': 2, 'cat': 2, 'this': 1, 'is': 1}


In [ ]:
# Write a function that takes a number and returns True
# if it is a palindrome, otherwise False
def is_pallindrome(n):
    s=str(n)
    return s==s[::-1]
number=int(input("enter the number:"))
print(is_pallindrome(number))


enter the number:121
True


In [ ]:
#Create a function that takes a temperature in Celsius and
#  returns it in Fahrenheit
def celsius_to_fahrenheit(celsius):
    return ((celsius*9/5)+32)
temp=int(input("enter the temperatue:"))
print("fahrenheit is:",celsius_to_fahrenheit(temp))


enter the temperatue:34
fahrenheit is: 93.2


#Assignment 9


In [ ]:
# Create a NumPy array with values from 1 to 10. Print the shape,
# dimension, and data type of the array
import numpy as np
arr=np.arange(1,11)
print("array:",arr)
print("array shape:",arr.shape)
print("dimensions:",arr.ndim)
print("data type:",arr.dtype)


array: [ 1  2  3  4  5  6  7  8  9 10]
array shape: (10,)
dimensions: 1
data type: int64


In [ ]:
#Create a 3x3 NumPy array of all zeros and another of all ones.
#  Then create a 3x3 identity matrix
zeros=np.zeros((3,3))
ones=np.ones((3,3))
identity=np.eye(3)
print("zeros array:\n",zeros)
print("ones aray:\n",ones)
print("identity matrix:\n",identity)


zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones aray:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Generate an array of 15 random integers between 10 and 100 using np.random.
# randint. Reshape it into a 3x5 matrix and print it.
arr=np.random.randint(10,101,size=15)
matrix=arr.reshape(3,5)
print(matrix)


[[68 98 89 55 96]
 [19 27 98 28 62]
 [77 94 60 75 91]]


In [ ]:
#Create a NumPy array from 1 to 20. Extract
# every 3rd element starting from index 1 using slicing
array1=np.arange(1,21)
result=array1[1::3]
print("every 3rd element from index 1 is:",result)


every 3rd element from index 1 is: [ 2  5  8 11 14 17 20]


In [ ]:
# Create two arrays: a = np.array([2, 4, 6, 8]) and b = np.array([1, 3, 5, 7]).
# Perform element-wise addition, multiplication, and compare which elements
#  in a are greater than in b.
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print("addition:",a+b)
print("multiplication:",a*b)
print("a>b:",a>b)


addition: [ 3  7 11 15]
multiplication: [ 2 12 30 56]
a>b: [ True  True  True  True]


In [ ]:
# Create a NumPy array with 20 random values (0 to 1) using np.random.rand().
# Find the mean, median, standard deviation, min, and max.
arr=np.random.rand(20)
print(arr)
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("std dev:",np.std(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))


[0.58988147 0.90326573 0.8339253  0.30803636 0.55430335 0.53923068
 0.58667126 0.343035   0.71271707 0.23140533 0.9326067  0.32917514
 0.77261107 0.51241069 0.13815334 0.66441593 0.5519725  0.39024704
 0.72412854 0.89899735]
mean: 0.5758594939674012
median: 0.5704873067296097
std dev: 0.22703961613848128
min: 0.1381533437667778
max: 0.9326067039154502


In [ ]:
#Given: arr = np.array([[3, 5], [7, 9]]).
# Find the sum across rows and columns using axis.
arr=np.array([[3, 5], [7, 9]])
print("sum across rows:",arr.sum(axis=1))
print("sum across columns:",arr.sum(axis=0))


sum across rows: [ 8 16]
sum across columns: [10 14]


In [ ]:
# Create a NumPy array of numbers from 10 to 30. Filter and print only the even
# numbers using boolean indexing.
arr=np.arange(10,31)
even=arr[arr%2==0]
print("even numbers are:",even)


even numbers are: [10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
#Generate an array of 10 random integers from 1 to 100. Replace all elements
# greater than 50 with-1.
arr=np.random.randint(1,101,10)
arr[arr>50]=-1
print("modified array:",arr)


modified array: [47 44 -1 -1 32 -1 32 -1 -1 -1]


In [ ]:
#Create two arrays: x = np.array([[1, 2], [3, 4]]) and y=np.array([[5, 6],
#  [7, 8]]). Stack them vertically and horizontally, then flatten the result
# into a 1D array
x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6],[7, 8]])
v_stack=np.vstack((x,y))
h_stack=np.hstack((x,y))
flattened=h_stack.flatten()
print("vertical stack:\n",v_stack)
print("horizontal stack:\n",h_stack)
print("flattened:",flattened)


vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]
flattened: [1 2 5 6 3 4 7 8]


#Assignment 10

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/amrit2711tech/Assignment/refs/heads/main/diamonds.csv')

df.head(10)


carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [ ]:
#Check the shape and column names of the dataset.
df.shape

(50000, 10)

In [ ]:
df.columns


Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [ ]:
#Find and fill missing numeric values with their respective column means.
df.describe()


carat         depth         table         price             x  \
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000   
mean       0.799444     61.753006     57.457830   3944.805440      5.734403   
std        0.475173      1.431088      2.232092   3997.938105      1.123077   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    951.000000      4.710000   
50%        0.700000     61.800000     57.000000   2410.000000      5.700000   
75%        1.040000     62.500000     59.000000   5351.000000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  50000.000000  50000.000000  
mean       5.737956      3.541056  
std        1.145579      0.707065  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [ ]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [ ]:
#filter rows where 'cut' id "ideal" and 'color' is "E"
filtered_df=df[(df['cut']=='Ideal')&(df['color']=='E')]
filtered_df

carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
76      0.26  Ideal     E    VVS2   62.9   58.0    554  4.02  4.06  2.54
82      0.70  Ideal     E     SI1   62.5   57.0   2757  5.70  5.72  3.57
100     0.59  Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35
102     0.74  Ideal     E     SI2   62.2   56.0   2761  5.80  5.84  3.62
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
49940   0.70  Ideal     E     SI1   61.7   55.0   2745  5.71  5.74  3.53
49942   0.51  Ideal     E    VVS1   61.9   54.0   2745  5.17  5.11  3.18
49954   0.56  Ideal     E    VVS1   62.1   56.0   2750  5.28  5.29  3.28
49978   0.77  Ideal     E     SI2   62.1   56.0   2753  5.84  5.86  3.63
49987   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54

[3628 rows x 10 columns]

In [ ]:
#Group by 'cut' and compute the average 'price' for each group
average_price = df.groupby('cut')['price'].mean()
average_price

cut
Fair         4329.705017
Good         3961.470266
Ideal        3463.090230
Premium      4607.382867
Very Good    3986.585594
Name: price, dtype: float64

In [ ]:
#Sort the data by 'carat' in descending order and show the top 5 rows.
carat=df.sort_values(['carat'],ascending=False).head(5)
print(carat)

       carat      cut color clarity  depth  table  price      x      y     z
25426   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
25624   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
25163   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
24102   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
24103   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24


In [ ]:
#convert the 'price' column to a NumPy array and find its mean,median and standard deviation
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/amrit2711tech/Assignment/refs/heads/main/diamonds.csv')

price_array = df['price'].to_numpy()
print(price_array)
mean_price = np.mean(price_array)
median_price = np.median(price_array)
std_price = np.std(price_array)
print(f"Mean: {mean_price}")
print(f"Median: {median_price}")
print(f"Standard Deviation: {std_price}")









[ 326  326  327 ... 2757 2757 2757]
Mean: 3944.80544
Median: 2410.0
Standard Deviation: 3997.8981250585175


In [ ]:
#Count diamonds with 'price>5000' and 'carat>1' using NumPy conditions
price_array = df['price'].to_numpy()
carat_array = df['carat'].to_numpy()
condition = (price_array>5000) & (carat_array>1)
count = np.sum(condition)
print("Number of diamonds with 'price>5000' and 'carat>1' is:",count)



Number of diamonds with 'price>5000' and 'carat>1' is: 12798


In [ ]:
# Create a new column `price_updated` by increasing `price` by 10% using NumPy
price_array=df['price'].to_numpy()
df['price_updated']=df['price']*1.10
print(df.head())

   carat      cut color clarity  depth  table  price     x     y     z  \
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   

   price_updated  
0          358.6  
1          358.6  
2          359.7  
3          367.4  
4          368.5  


In [ ]:
#Create a `volume` column as `x*y*z` and find the average `price` where `volume > 50`
df['volume']=df['x']*df['y']*df['z']
print(df[df['volume']>50]['price'].mean())
df['volume']

4195.133420860057


0         38.202030
1         34.505856
2         38.076885
3         46.724580
4         51.917250
            ...    
49995    115.920000
49996    118.110175
49997    114.449728
49998    140.766120
49999    124.568444
Name: volume, Length: 50000, dtype: float64

#Assignment 11

In [ ]:
# Calculate the number of days with missing temperature
#data (Max, Min, or Mean).
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/amrit2711tech/Assignment/refs/heads/main/nyc_weather.csv')
df.head()


EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [ ]:
df.describe()

Temperature   DewPoint   Humidity  Sea Level PressureIn  \
count    31.000000  31.000000  31.000000             31.000000   
mean     34.677419  17.838710  51.677419             29.992903   
std       7.639315  11.378626  11.634395              0.237237   
min      20.000000  -3.000000  33.000000             29.520000   
25%      29.000000  10.000000  44.500000             29.855000   
50%      35.000000  18.000000  50.000000             30.010000   
75%      39.500000  23.000000  55.000000             30.140000   
max      50.000000  46.000000  78.000000             30.570000   

       VisibilityMiles  WindSpeedMPH  CloudCover  WindDirDegrees  
count        31.000000     28.000000   31.000000       31.000000  
mean          9.193548      6.892857    3.129032      247.129032  
std           1.939405      2.871821    2.629853       92.308086  
min           1.000000      2.000000    0.000000       34.000000  
25%           9.000000      5.000000    1.000000      238.000000  
50%          10.000000      6.500000    3.000000      281.000000  
75%          10.000000      8.000000    4.500000      300.000000  
max          10.000000     16.000000    8.000000      345.000000

In [ ]:
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
import numpy as np
df.loc[[4,6],"Temperature"]=np.nan
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016         38.0        23        52                 30.03   
1    1/2/2016         36.0        18        46                 30.02   
2    1/3/2016         40.0        21        47                 29.86   
3    1/4/2016         25.0         9        44                 30.05   
4    1/5/2016          NaN        -3        41                 30.57   
5    1/6/2016         33.0         4        35                 30.50   
6    1/7/2016          NaN        11        33                 30.28   
7    1/8/2016         39.0        29        64                 30.20   
8    1/9/2016         44.0        38        77                 30.16   
9   1/10/2016         50.0        46        71                 29.59   
10  1/11/2016         33.0         8        37                 29.92   
11  1/12/2016         35.0        15        53                 29.85   
12  1/13/2016         26.0         4        42                 29.94   
13  1/14/2016         30.0        12        47                 29.95   
14  1/15/2016         43.0        31        62                 29.82   
15  1/16/2016         47.0        37        70                 29.52   
16  1/17/2016         36.0        23        66                 29.78   
17  1/18/2016         25.0         6        53                 29.83   
18  1/19/2016         22.0         3        42                 30.03   
19  1/20/2016         32.0        15        49                 30.13   
20  1/21/2016         31.0        11        45                 30.15   
21  1/22/2016         26.0         6        41                 30.21   
22  1/23/2016         26.0        21        78                 29.77   
23  1/24/2016         28.0        11        53                 29.92   
24  1/25/2016         34.0        18        54                 30.25   
25  1/26/2016         43.0        29        56                 30.03   
26  1/27/2016         41.0        22        45                 30.03   
27  1/28/2016         37.0        20        51                 29.90   
28  1/29/2016         36.0        21        50                 29.58   
29  1/30/2016         34.0        16        46                 30.01   
30  1/31/2016         46.0        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
df['Temperature'] = df['Temperature'].fillna(df['Temperature'].mean())
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016    38.000000        23        52                 30.03   
1    1/2/2016    36.000000        18        46                 30.02   
2    1/3/2016    40.000000        21        47                 29.86   
3    1/4/2016    25.000000         9        44                 30.05   
4    1/5/2016    35.034483        -3        41                 30.57   
5    1/6/2016    33.000000         4        35                 30.50   
6    1/7/2016    35.034483        11        33                 30.28   
7    1/8/2016    39.000000        29        64                 30.20   
8    1/9/2016    44.000000        38        77                 30.16   
9   1/10/2016    50.000000        46        71                 29.59   
10  1/11/2016    33.000000         8        37                 29.92   
11  1/12/2016    35.000000        15        53                 29.85   
12  1/13/2016    26.000000         4        42                 29.94   
13  1/14/2016    30.000000        12        47                 29.95   
14  1/15/2016    43.000000        31        62                 29.82   
15  1/16/2016    47.000000        37        70                 29.52   
16  1/17/2016    36.000000        23        66                 29.78   
17  1/18/2016    25.000000         6        53                 29.83   
18  1/19/2016    22.000000         3        42                 30.03   
19  1/20/2016    32.000000        15        49                 30.13   
20  1/21/2016    31.000000        11        45                 30.15   
21  1/22/2016    26.000000         6        41                 30.21   
22  1/23/2016    26.000000        21        78                 29.77   
23  1/24/2016    28.000000        11        53                 29.92   
24  1/25/2016    34.000000        18        54                 30.25   
25  1/26/2016    43.000000        29        56                 30.03   
26  1/27/2016    41.000000        22        45                 30.03   
27  1/28/2016    37.000000        20        51                 29.90   
28  1/29/2016    36.000000        21        50                 29.58   
29  1/30/2016    34.000000        16        46                 30.01   
30  1/31/2016    46.000000        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
# Group the data by 'Events' and calculate the average mean temperature for each event type.
average_mean_temp = df.groupby('Events')['Temperature'].mean()
average_mean_temp

Events
Fog-Snow    31.000000
Rain        45.500000
Snow        26.333333
Name: Temperature, dtype: float64

In [ ]:
# Create a new column 'Feels Like' using the formula:
#(Max TemperatureF + Min TemperatureF) / 2 - (Mean Humidity / 100) * Wind SpeedMPH.
max_temperature = df['Temperature'].max()
min_temperature = df['Temperature'].min()
df['WindSpeedMPH'] = df['WindSpeedMPH'].fillna(df['WindSpeedMPH'].mean())
df['Feels Like'] = ((max_temperature + min_temperature) / 2 - (df['Humidity'] / 100) * df['WindSpeedMPH'])
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016         38.0        23        52                 30.03   
1    1/2/2016         36.0        18        46                 30.02   
2    1/3/2016         40.0        21        47                 29.86   
3    1/4/2016         25.0         9        44                 30.05   
4    1/5/2016          NaN        -3        41                 30.57   
5    1/6/2016         33.0         4        35                 30.50   
6    1/7/2016          NaN        11        33                 30.28   
7    1/8/2016         39.0        29        64                 30.20   
8    1/9/2016         44.0        38        77                 30.16   
9   1/10/2016         50.0        46        71                 29.59   
10  1/11/2016         33.0         8        37                 29.92   
11  1/12/2016         35.0        15        53                 29.85   
12  1/13/2016         26.0         4        42                 29.94   
13  1/14/2016         30.0        12        47                 29.95   
14  1/15/2016         43.0        31        62                 29.82   
15  1/16/2016         47.0        37        70                 29.52   
16  1/17/2016         36.0        23        66                 29.78   
17  1/18/2016         25.0         6        53                 29.83   
18  1/19/2016         22.0         3        42                 30.03   
19  1/20/2016         32.0        15        49                 30.13   
20  1/21/2016         31.0        11        45                 30.15   
21  1/22/2016         26.0         6        41                 30.21   
22  1/23/2016         26.0        21        78                 29.77   
23  1/24/2016         28.0        11        53                 29.92   
24  1/25/2016         34.0        18        54                 30.25   
25  1/26/2016         43.0        29        56                 30.03   
26  1/27/2016         41.0        22        45                 30.03   
27  1/28/2016         37.0        20        51                 29.90   
28  1/29/2016         36.0        21        50                 29.58   
29  1/30/2016         34.0        16        46                 30.01   
30  1/31/2016         46.0        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10      8.000000               0           5       NaN   
1                10      7.000000               0           3       NaN   
2                10      8.000000               0           1       NaN   
3                10      9.000000               0           3       NaN   
4                10      5.000000               0           0       NaN   
5                10      4.000000               0           0       NaN   
6                10      2.000000               0           3       NaN   
7                10      4.000000               0           8       NaN   
8                 9      8.000000               T           8      Rain   
9                 4      6.892857             1.8           7      Rain   
10               10      6.892857               0           1       NaN   
11               10      6.000000               T           4       NaN   
12               10     10.000000               0           0       NaN   
13               10      5.000000               T           7       NaN   
14                9      5.000000               T           2       NaN   
15                8      7.000000            0.24           7      Rain   
16                8      6.000000            0.05           6  Fog-Snow   
17                9     12.000000               T           2      Snow   
18               10     11.000000               0           1       NaN   
19               10      6.000000               0           2       NaN   
20               10      6.000000               0           1       NaN   
21                9      6.892857            0.01      

In [ ]:
#Find the top 3 dates with the highest temperature difference (Max - Min).
df['Temperature_diff'] = ((max_temperature) - (min_temperature))
df_sorted = df.sort_values(by='Temperature_diff', ascending=False)
print("Top 3 dates with the highest temperature difference:")
print(df_sorted[['EST', 'Temperature_diff']].head(3))

Top 3 dates with the highest temperature difference:
        EST  Temperature_diff
0  1/1/2016              28.0
1  1/2/2016              28.0
2  1/3/2016              28.0


In [ ]:
#Identify the longest streak of days with no precipitation.
no_precipitation = (df['PrecipitationIn']==0)|(df['PrecipitationIn']=='T')
longest_streak = 0
current_streak = 0
for day in no_precipitation:
    if day:
        current_streak += 1
    else:
        longest_streak = max(longest_streak, current_streak)
        current_streak = 0

# After the loop, check if the last streak was the longest
longest_streak = max(longest_streak, current_streak)

print("Longest streak of days with no precipitation:", longest_streak)

Longest streak of days with no precipitation: 2


In [ ]:
#Calculate the total precipitation for days with both Rain and Fog events
# Filter rows where Events contain both 'Rain' and 'Fog'
rain_fog_days = df[df['Events'].str.contains('Rain') & df['Events'].str.contains('Fog')]

# Calculate total precipitation for those days
total_precip = rain_fog_days['PrecipitationIn'].sum()

print(f"Total precipitation on days with both Rain and Fog: {total_precip}")

Total precipitation on days with both Rain and Fog: 0


In [ ]:
# Convert the 'EST' column to datetime format and extract the week number for each date.
df['EST'] = pd.to_datetime(df['EST'])
df['Week_Number'] = df['EST'].dt.isocalendar().week
print(df[['EST', 'Week_Number']].head(31))

          EST  Week_Number
0  2016-01-01           53
1  2016-01-02           53
2  2016-01-03           53
3  2016-01-04            1
4  2016-01-05            1
5  2016-01-06            1
6  2016-01-07            1
7  2016-01-08            1
8  2016-01-09            1
9  2016-01-10            1
10 2016-01-11            2
11 2016-01-12            2
12 2016-01-13            2
13 2016-01-14            2
14 2016-01-15            2
15 2016-01-16            2
16 2016-01-17            2
17 2016-01-18            3
18 2016-01-19            3
19 2016-01-20            3
20 2016-01-21            3
21 2016-01-22            3
22 2016-01-23            3
23 2016-01-24            3
24 2016-01-25            4
25 2016-01-26            4
26 2016-01-27            4
27 2016-01-28            4
28 2016-01-29            4
29 2016-01-30            4
30 2016-01-31            4


In [ ]:
#Find the month with the highest average wind speed.
df['Month'] = df['EST'].dt.month
monthly_avg_wind = df.groupby('Month')['WindSpeedMPH'].mean()
max_month = monthly_avg_wind.idxmax()
max_value = monthly_avg_wind.max()

print(f"Month with highest average wind speed: {max_month}")
print(f"Average wind speed in that month: {max_value:.2f} MPH")

Month with highest average wind speed: 1
Average wind speed in that month: 6.89 MPH


In [ ]:
#Detect outliers in the 'Max TemperatureF' column using IQR method.

In [ ]:
#Create a line plot of mean temperature over time and annotate the highest peak